<?php

/**
 * Theme functions. Initializes the Vamtam Framework.
 *
 * @package vamtam/morz
 */

define( 'VAMTAM_ENVATO_THEME_ID', '21623322' );

require_once get_template_directory() . '/vamtam/classes/framework.php';

new VamtamFramework( array(
	'name' => 'morz',
	'slug' => 'morz',
) );

// only for one page home demos
function vamtam_onepage_menu_hrefs( $atts, $item, $args ) {
	if ( 'custom' === $item->type && 0 === strpos( $atts['href'], '/#' ) ) {
		$atts['href'] = $GLOBALS['vamtam_inner_path'] . $atts['href'];
	}
	return $atts;
}

if ( ( $path = parse_url( get_home_url(), PHP_URL_PATH ) ) !== null ) {
	$GLOBALS['vamtam_inner_path'] = untrailingslashit( $path );
	add_filter( 'nav_menu_link_attributes', 'vamtam_onepage_menu_hrefs', 10, 3 );
}

remove_action( 'admin_head', 'jordy_meow_flattr', 1 );

require_once VAMTAM_DIR . 'customizer/setup.php';

require_once VAMTAM_DIR . 'customizer/preview.php';

// this filter fixes some invalid HTML generated by the third-party plugins
add_filter( 'vamtam_escaped_shortcodes', 'vamtam_shortcode_compat_fix' );
function vamtam_shortcode_compat_fix( $codes ) {
	$codes[] = 'gallery';
	$codes[] = 'fl_builder_insert_layout';

	return $codes;
}

// Envato Hosted compatibility
add_filter( 'option_' . VamtamFramework::get_purchase_code_option_key(), 'vamtam_envato_hosted_license_key' );
function vamtam_envato_hosted_license_key( $value ) {
	if ( defined( 'SUBSCRIPTION_CODE' ) ) {
		return SUBSCRIPTION_CODE;
	}

	return $value;
}

if ( class_exists( 'Vamtam_Importers' ) && is_callable( array( 'Vamtam_Importers', 'set_menu_locations' ) ) ) {
	Vamtam_Importers::set_menu_locations();
}

function post_title_shortcode(){
    return get_the_title();
}
add_shortcode('post_title','post_title_shortcode');

function post_br_tel_shortcode(){
	$tel	= do_shortcode('[acf field="br_telefon"]');
	$fax	= do_shortcode('[acf field="br_fax"]');
	$html	= '';

	if ($tel) {
		$html .= '<h4>tel. '.$tel.'</h4>';
	}

	if ($fax) {
		$html .= '<h4>faks '.$fax.'</h4>';
	}

	return $html;
}
add_shortcode('post_br_tel','post_br_tel_shortcode');

function post_br_emailwww_shortcode() {
	/*
	<h4>E-mail: <a href="mailto:[acf field=br_email]">[acf field="br_email"]</a></h4>
	<p><a href="http://[acf field=br_www]" target="_blank" rel="noopener noreferrer">[acf field="br_www"]</a></p>
	*/
	$email	= do_shortcode('[acf field="br_email"]');
	$www	= do_shortcode('[acf field="br_www"]');
	$html	= '';

	if ($email) {
		$html .= '<h4>E-mail: <a href="mailto:'.$email.'">'.$email.'</a></h4> ';
	}

	if ($www) {
		$html .= '<p><a href="http://'.$www.'" target="_blank" rel="noopener noreferrer">'.$www.'</a></p> ';
	}

	return $html;
}
add_shortcode('post_br_email_www','post_br_emailwww_shortcode');

function post_br_address_shortcode() {
	/*
	<h4>[acf field="br_adres"]</h4>
	<h4>[acf field="br_kod_pocztowy"] [acf field="br_miasto"]</h4>
	<p>województwo [acf field="br_wojewodztwo"]</p>
	*/
	$html	= do_shortcode('<h4>[acf field="br_adres"]</h4> <h4>[acf field="br_kod_pocztowy"] [acf field="br_miasto"]</h4> <p>województwo [acf field="br_wojewodztwo"]</p>');

	return $html;
}
add_shortcode('post_br_address','post_br_address_shortcode');

function post_dl_tel_shortcode(){
	$tel	= do_shortcode('[acf field="dl_telefon"]');
	$fax	= do_shortcode('[acf field="dl_fax"]');
	$html	= '';

	if ($tel) {
		$html .= '<h4>tel. '.$tel.'</h4>';
	}

	if ($fax) {
		$html .= '<h4>faks '.$fax.'</h4>';
	}

	return $html;
}
add_shortcode('post_dl_tel','post_dl_tel_shortcode');

function post_dl_emailwww_shortcode() {
	/*
	<h4>E-mail: <a href="mailto:[acf field=dl_email]">[acf field="dl_email"]</a></h4>
	<p><a href="http://[acf field=dl_www]" target="_blank" rel="noopener noreferrer">[acf field="dl_www"]</a></p>
	*/
	$email	= do_shortcode('[acf field="dl_email"]');
	$www	= do_shortcode('[acf field="dl_www"]');
	$html	= '';

	if ($email) {
		$html .= '<h4>E-mail: <a href="mailto:'.$email.'">'.$email.'</a></h4> ';
	}

	if ($www) {
		$html .= '<p><a href="http://'.$www.'" target="_blank" rel="noopener noreferrer">'.$www.'</a></p> ';
	}

	return $html;
}
add_shortcode('post_dl_email_www','post_dl_emailwww_shortcode');

function post_dl_address_shortcode() {
	/*
	<h4>[acf field="dl_adres"]</h4>
	<h4>[acf field="dl_kod_pocztowy"] [acf field="dl_miasto"]</h4>
	<p>województwo [acf field="dl_wojewodztwo"]</p>
	*/
	$html	= do_shortcode('<h4>[acf field="dl_adres"]</h4> <h4>[acf field="dl_kod_pocztowy"] [acf field="dl_miasto"]</h4> <p>województwo [acf field="dl_wojewodztwo"]</p>');

	return $html;
}
add_shortcode('post_dl_address','post_dl_address_shortcode');

function post_dl_table_shortcode($atts = [], $content = null, $tag = '') {

    $atts = array_change_key_case((array)$atts, CASE_LOWER);
 
	$dl_atts = shortcode_atts(['field' => '', 'value' => ''], $atts, $tag);
	// [acf field="dl_produkty_serwis"]
	$results = explode(', ', do_shortcode('[acf field="'.$dl_atts['field'].'"]'));

	if (in_array($dl_atts['value'], $results)) {
		$html = '<span class="pp-icon icon-circle_full_check" style="color: #44c400;"> </span>';
	}
	else {
		$html = '<span class="fas fa-times-circle" style="color: #cccccc;"> </span>';
	}

	return($html);
}

function post_dl_table_init()
{
    add_shortcode('post_dl_table', 'post_dl_table_shortcode');
}
 
add_action('init', 'post_dl_table_init');

function excerpt_br_shortcode() {
	$content	= '[acf field="br_adres"]<br/>
	[acf field="br_kod_pocztowy"] [acf field="br_miasto"]<br/>
	województwo [acf field="br_wojewodztwo"]<br/>';
	$tel		= do_shortcode('[acf field="br_telefon"]');
	$fax		= do_shortcode('[acf field="br_fax"]');
	$email		= do_shortcode('[acf field="br_email"]');
	$www		= do_shortcode('[acf field="br_www"]');

	$html = do_shortcode($content);

	if ($tel) {
		$html .= 'tel. '.$tel.'<br/>';
	}

	if ($fax) {
		$html .= 'faks '.$fax.'<br/>';
	}

	if ($email) {
		$html .= '<a href="mailto:'.$email.'">adres e-mail</a>';
	}

	if ($www) {
		if ($email) {
			$html .= ' | ';
		}
		$html .= '<a href="http://'.$www.'" target="_blank" rel="noopener noreferrer">strona www</a>';
	}

	return $html;
}
add_shortcode('excerpt_br','excerpt_br_shortcode');

function map_address_br_shortcode() {
	$address = urlencode(do_shortcode('[acf field="br_adres"]+[acf field="br_kod_pocztowy"]+[acf field="br_miasto"]'));

	return '<iframe src="https://maps.google.com/maps?q='.$address.'&iwloc=near&output=embed" style="border:0;width:100%;" height="300" frameborder="0"></iframe>';
}
add_shortcode('map_address_br','map_address_br_shortcode');

function excerpt_dl_shortcode() {
	$badges		= [['title' => 'dystrybutor', 'url' => '/wp-content/uploads/2019/07/DYS-1.png'],
					['title' => 'autoryzowany serwis wapro B2C', 'url' => '/wp-content/uploads/2019/07/ASA-1.png'],
					['title' => 'autoryzowane centrum serwisowe', 'url' => '/wp-content/uploads/2019/08/ASC-1.png'],
					['title' => 'autoryzowane centrum szkoleniowe', 'url' => '/wp-content/uploads/2019/08/ACS-1.png'],
					['title' => 'autoryzowany serwis', 'url' => '/wp-content/uploads/2019/08/AS-1.png'],
					['title' => 'złoty partner', 'url' => '/wp-content/uploads/2019/08/PZ-1.png'],
					['title' => 'srebrny partner', 'url' => '/wp-content/uploads/2019/08/PS-1.png'],
					['title' => 'brązowy partner', 'url' => '/wp-content/uploads/2019/08/PB-1.png'],
					['title' => 'punkt sprzedaży', 'url' => '/wp-content/uploads/2019/08/POS-1.png'],
					['title' => 'złoty dealer', 'url' => '/wp-content/uploads/2019/08/DZ-1.png'],
					['title' => 'srebrny dealer', 'url' => '/wp-content/uploads/2019/08/DS-1.png'],
					['title' => 'brązowy dealer', 'url' => '/wp-content/uploads/2019/08/DB-1.png']];

	$content	= '[acf field="dl_adres"]<br/>
	[acf field="dl_kod_pocztowy"] [acf field="dl_miasto"]<br/>
	województwo [acf field="dl_wojewodztwo"]<br/>';
	$tel		= do_shortcode('[acf field="dl_telefon"]');
	$fax		= do_shortcode('[acf field="dl_fax"]');
	$email		= do_shortcode('[acf field="dl_email"]');
	$www		= do_shortcode('[acf field="dl_www"]');

	$html = do_shortcode($content);

	if ($tel) {
		$html .= 'tel. '.$tel.'<br/>';
	}

	if ($fax) {
		$html .= 'faks '.$fax.'<br/>';
	}

	if ($email) {
		$html .= '<a href="mailto:'.$email.'">adres e-mail</a>';
	}

	if ($www) {
		if ($email) {
			$html .= ' | ';
		}
		$html .= '<a href="http://'.$www.'" target="_blank" rel="noopener noreferrer">strona www</a>';
	}

	$etykiety = explode(', ', do_shortcode('[acf field="dl_etykieta"]'));

	if (count($etykiety)) {
		$html .= '<br/>';
	}

	foreach ($badges as $badge) {
		if (in_array($badge['title'], $etykiety)) {
			$html .= '<div style="width:60%;padding-top:5px"><img src="'.$badge['url'].'" alt="'.$badge['title'].'" height="30px" border="0" align="middle" /></div>';
		}
	}

	return $html;
}
add_shortcode('excerpt_dl','excerpt_dl_shortcode');

function map_address_dl_shortcode() {
	$address = urlencode(do_shortcode('[acf field="dl_adres"]+[acf field="dl_kod_pocztowy"]+[acf field="dl_miasto"]'));

	return '<iframe src="https://maps.google.com/maps?q='.$address.'&iwloc=near&output=embed" style="border:0;width:100%;" height="300" frameborder="0"></iframe>';
}
add_shortcode('map_address_dl','map_address_dl_shortcode');

function map_obszar_br_shortcode() {
	$voivodeships = [['id' => 'pl2', 'class' => 'pl1', 'url' => 'dolnoslaskie', 'title' => 'dolnośląskie'],
					['id' => 'pl3', 'class' => 'pl2', 'url' => 'kujawsko-pomorskie', 'title' => 'kujawsko-pomorskie'],
					['id' => 'pl4', 'class' => 'pl3', 'url' => 'lubelskie', 'title' => 'lubelskie'],
					['id' => 'pl5', 'class' => 'pl4', 'url' => 'lubuskie', 'title' => 'lubuskie'],
					['id' => 'pl15', 'class' => 'pl5', 'url' => 'lodzkie', 'title' => 'łódzkie'],
					['id' => 'pl7', 'class' => 'pl6', 'url' => 'malopolskie', 'title' => 'małopolskie'],
					['id' => 'pl6', 'class' => 'pl7', 'url' => 'mazowieckie', 'title' => 'mazowieckie'],
					['id' => 'pl8', 'class' => 'pl8', 'url' => 'opolskie', 'title' => 'opolskie'],
					['id' => 'pl9', 'class' => 'pl9', 'url' => 'podkarpackie', 'title' => 'podkarpackie'],
					['id' => 'pl10', 'class' => 'pl10', 'url' => 'podlaskie', 'title' => 'podlaskie'],
					['id' => 'pl11', 'class' => 'pl11', 'url' => 'pomorskie', 'title' => 'pomorskie'],
					['id' => 'pl16', 'class' => 'pl12', 'url' => 'slaskie', 'title' => 'śląskie'],
					['id' => 'pl17', 'class' => 'pl13', 'url' => 'swietokrzyskie', 'title' => 'świętokrzyskie'],
					['id' => 'pl12', 'class' => 'pl14', 'url' => 'warminsko-mazurskie', 'title' => 'warmińsko-mazurskie'],
					['id' => 'pl13', 'class' => 'pl15', 'url' => 'wielkopolskie', 'title' => 'wielkopolskie'],
					['id' => 'pl14', 'class' => 'pl16', 'url' => 'zachodniopomorskie', 'title' => 'zachodniopomorskie']];

	$obszar = explode(', ', do_shortcode('[acf field="br_obszar_dzialania"]'));

	$html = '<ul class="poland">';

	foreach ($voivodeships as $voivodeship) {
		$html .= '<li id="'.$voivodeship['id'].'" class="'.$voivodeship['class'];

		if (in_array($voivodeship['title'], $obszar)) {
			$html .= ' active-region';
		}

		$html .= '"><a href="#'.$voivodeship['url'].'" title="'.$voivodeship['title'].'">'.$voivodeship['title'].' <span class="bg"></span></a></li>';
	}

	$html .= '</ul>';

	return $html;
}
add_shortcode('map_obszar_br','map_obszar_br_shortcode');

function map_obszar_dl_shortcode() {
	$voivodeships = [['id' => 'pl2', 'class' => 'pl1', 'url' => 'dolnoslaskie', 'title' => 'dolnośląskie'],
					['id' => 'pl3', 'class' => 'pl2', 'url' => 'kujawsko-pomorskie', 'title' => 'kujawsko-pomorskie'],
					['id' => 'pl4', 'class' => 'pl3', 'url' => 'lubelskie', 'title' => 'lubelskie'],
					['id' => 'pl5', 'class' => 'pl4', 'url' => 'lubuskie', 'title' => 'lubuskie'],
					['id' => 'pl15', 'class' => 'pl5', 'url' => 'lodzkie', 'title' => 'łódzkie'],
					['id' => 'pl7', 'class' => 'pl6', 'url' => 'malopolskie', 'title' => 'małopolskie'],
					['id' => 'pl6', 'class' => 'pl7', 'url' => 'mazowieckie', 'title' => 'mazowieckie'],
					['id' => 'pl8', 'class' => 'pl8', 'url' => 'opolskie', 'title' => 'opolskie'],
					['id' => 'pl9', 'class' => 'pl9', 'url' => 'podkarpackie', 'title' => 'podkarpackie'],
					['id' => 'pl10', 'class' => 'pl10', 'url' => 'podlaskie', 'title' => 'podlaskie'],
					['id' => 'pl11', 'class' => 'pl11', 'url' => 'pomorskie', 'title' => 'pomorskie'],
					['id' => 'pl16', 'class' => 'pl12', 'url' => 'slaskie', 'title' => 'śląskie'],
					['id' => 'pl17', 'class' => 'pl13', 'url' => 'swietokrzyskie', 'title' => 'świętokrzyskie'],
					['id' => 'pl12', 'class' => 'pl14', 'url' => 'warminsko-mazurskie', 'title' => 'warmińsko-mazurskie'],
					['id' => 'pl13', 'class' => 'pl15', 'url' => 'wielkopolskie', 'title' => 'wielkopolskie'],
					['id' => 'pl14', 'class' => 'pl16', 'url' => 'zachodniopomorskie', 'title' => 'zachodniopomorskie']];

	$obszar = explode(', ', do_shortcode('[acf field="dl_obszar_dzialania"]'));

	$html = '<ul class="poland">';

	foreach ($voivodeships as $voivodeship) {
		$html .= '<li id="'.$voivodeship['id'].'" class="'.$voivodeship['class'];

		if (in_array($voivodeship['title'], $obszar)) {
			$html .= ' active-region';
		}

		$html .= '"><a href="#'.$voivodeship['url'].'" title="'.$voivodeship['title'].'">'.$voivodeship['title'].' <span class="bg"></span></a></li>';
	}

	$html .= '</ul>';

	return $html;
}
add_shortcode('map_obszar_dl','map_obszar_dl_shortcode');

function badges_dl_shortcode() {
	$badges		= [['title' => 'dystrybutor', 'url' => '/wp-content/uploads/2019/07/DYS-1.png'],
					['title' => 'autoryzowany serwis wapro B2C', 'url' => '/wp-content/uploads/2019/07/ASA-1.png'],
					['title' => 'autoryzowane centrum serwisowe', 'url' => '/wp-content/uploads/2019/08/ASC-1.png'],
					['title' => 'autoryzowane centrum szkoleniowe', 'url' => '/wp-content/uploads/2019/08/ACS-1.png'],
					['title' => 'autoryzowany serwis', 'url' => '/wp-content/uploads/2019/08/AS-1.png'],
					['title' => 'złoty partner', 'url' => '/wp-content/uploads/2019/08/PZ-1.png'],
					['title' => 'srebrny partner', 'url' => '/wp-content/uploads/2019/08/PS-1.png'],
					['title' => 'brązowy partner', 'url' => '/wp-content/uploads/2019/08/PB-1.png'],
					['title' => 'punkt sprzedaży', 'url' => '/wp-content/uploads/2019/08/POS-1.png'],
					['title' => 'złoty dealer', 'url' => '/wp-content/uploads/2019/08/DZ-1.png'],
					['title' => 'srebrny dealer', 'url' => '/wp-content/uploads/2019/08/DS-1.png'],
					['title' => 'brązowy dealer', 'url' => '/wp-content/uploads/2019/08/DB-1.png']];
	$html		= '';

	$etykiety	= explode(', ', do_shortcode('[acf field="dl_etykieta"]'));

	foreach ($badges as $badge) {
		if (in_array($badge['title'], $etykiety)) {
			$html .= '<img src="'.$badge['url'].'" alt="'.$badge['title'].'" border="0" align="middle" style="width: 212px;margin-right: 20px;" />';
		}
	}

	return $html;
}
add_shortcode('badges_dl','badges_dl_shortcode');

add_filter( 'wpcf7_validate_number*', 'custom_online_number_validation_filter', 20, 2 );
 
function custom_online_number_validation_filter( $result, $tag ) {
	$tags = ['number-mag', 'number-mag-biznes', 'number-fakir', 'number-kaper', 'number-gang', 'number-best',
			'number-aukcje', 'number-analizy', 'number-mobile', 'number-jpk-biznes', 'number-jpk'];
	if ( in_array($tag->name, $tags) ) {
		$sum = 0;

		foreach ($tags as $item) {
			$sum += intval($_POST[$item]);
		}
 
        if ( $sum <= 0 ) {
            $result->invalidate( $tag, "Proszę wybrać conajmniej jeden program!" );
		}

		if (!isset($_POST['posiada-online']) and intval($_POST['number-jpk-biznes']) > 0 and intval($_POST['number-mag']) == 0 and 
			intval($_POST['number-fakir']) == 0 and intval($_POST['number-kaper']) == 0) {
			$result->invalidate( $tag, "Jeżeli wybrałeś WAPRO JPK musisz zaznaczyć WAPRO Mag, WAPRO Fakir lub WAPRO Kaper." );
		}

		if (!isset($_POST['posiada-online']) and intval($_POST['number-jpk']) > 0 and intval($_POST['number-mag']) == 0 and 
			intval($_POST['number-fakir']) == 0 and intval($_POST['number-kaper']) == 0) {
			$result->invalidate( $tag, "Jeżeli wybrałeś WAPRO JPK Biuro musisz zaznaczyć WAPRO Mag, WAPRO Fakir lub WAPRO Kaper." );
		}

		if (intval($_POST['number-jpk']) > 0 and intval($_POST['number-jpk-biznes']) > 0) {
			$result->invalidate( $tag, "Jeżeli zaznaczyłeś WAPRO JPK Biznes to nie możesz zaznaczyć WAPRO JPK Biuro." );
		}
    }
 
    return $result;
}
